(() => {
  const hexBytes = hex => Uint8Array.from(hex.match(/../g), part => parseInt(part, 16));
  for (const section of document.querySelectorAll('.article-lock')) {
    const form = section.querySelector('form');
    const status = form.querySelector('[role=status]');
    form.addEventListener('submit', async event => {
      event.preventDefault();
      const button = form.querySelector('button');
      button.disabled = true;
      status.textContent = '正在解锁…';
      try {
        if (!globalThis.crypto?.subtle) throw new Error('CRYPTO_UNAVAILABLE');
        const payload = JSON.parse(section.querySelector('.article-lock-data').textContent);
        if (payload.version !== 1) throw new Error('UNSUPPORTED_VERSION');
        const material = await crypto.subtle.importKey('raw', new TextEncoder().encode(form.elements.password.value), 'PBKDF2', false, ['deriveKey']);
        const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt: hexBytes(payload.salt), iterations: 210000, hash: 'SHA-256' }, material, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
        const bytes = Uint8Array.from(atob(payload.ciphertext), char => char.charCodeAt(0));
        const clear = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: hexBytes(payload.iv) }, key, bytes);
        // Only HTML generated by the site's Markdown renderer is encrypted.
        section.innerHTML = new TextDecoder().decode(clear);
      } catch (error) {
        status.textContent = error.message === 'CRYPTO_UNAVAILABLE' ? '此浏览器无法解锁，请使用 HTTPS 地址和新版浏览器。' : '密码不正确或内容无法解锁，请核对密码后重试。';
      } finally { button.disabled = false; }
    });
  }
})();
